### ISSUE TITLE
Remote search suggestions not showing up.

### ISSUE THREAD

**Issue by Phmurrph** [bravepipeproject/BraveNewPipeLegacy#2]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

BraveNewPipe 0.23.3-2.1.1-1

### Steps to reproduce the bug

1. Go to the search bar.
2. Introduce any character.

### Expected behavior

Suggest possible desired search.

### Actual behavior

It doesn't show anything.

### Screenshots/Screen recordings

![Screenshot_2023-08-16-17-42-26-1](https://github.com/bravenewpipe/BraveNewPipeLegacy/assets/140580407/6984e269-92b3-4c5f-bcf6-ab1367a5b5e3)

**Comment by evermind-zz** [comment]
are you talking about YouTube?  Does an earlier version work?

**Comment by Phmurrph** [comment]
> are you talking about YouTube? Does an earlier version work?

Yes, sorry for not specifying that (I'm still learning). Both Soundcloud and Bandcamp seem to work just fine.
The previous version worked well.

**Comment by evermind-zz** [comment]
the error occurs due to java 8 stream stuff not available on kitkat:

[suggestion-exception.txt](https://github.com/bravenewpipe/BraveNewPipeLegacy/files/12369202/suggestion-exception.txt)

I'll look into it. But no time at the moment
